version: '3'

services:
    backend:
        build: .
        image: archiezgg/cashcalc-backend
        container_name: cashcalc-backend
        ports:
            - "8080:8080"
        environment:
            PORT: "8080"
            MONGODB_URI: ${CASHCALC_MONGO_URI}
            POSTGRES_URL: "postgres://cash:kek@postgres:5432/cashcalc"
            REDIS_URL: "redis://redis:6379"
            ACCESS_KEY: "test_access_key"
            REFRESH_KEY: "test_refresh_key"
            ENVIRONMENT: "DEV"
        depends_on:
            - postgres
            - redis
    postgres:
        image: postgres:latest
        container_name: cashcalc-postgres
        environment:
            POSTGRES_USER: "cash"
            POSTGRES_PASSWORD: "kek"
            POSTGRES_DB: "cashcalc"
    redis:
        image: redis:latest
        container_name: cashcalc-redis