version: '3'

services:
    backend:
        build: .
        image: archiezgg/cashcalc-backend
        container_name: cashcalc-backend
        ports:
            - "8080:8080"
        environment:
            PORT: "8080"
            MONGODB_URI: "mongodb://mongo:27017/cashcalc"
            REDIS_URL: "redis://redis:6379"
            ACCESS_KEY: "test_access_key"
            REFRESH_KEY: "test_refresh_key"
        depends_on:
            - mongo
            - redis
    mongo:
        build:
            context: local_dev/mongo-cashcalc
        image: archiezgg/cashcalc-mongo
        container_name: cashcalc-mongo

    redis:
        image: redis:latest
        container_name: cashcalc-redis