version: '3'

services:
    backend:
        build: .
        image: archiezgg/cashcalc-backend
        container_name: cashcalc-backend
        ports:
            - "8080:8080"
        environment:
            PORT: "8080"
            MONGODB_URI: ${CASHCALC_MONGO_URI}
            REDIS_URL: "redis://redis:6379"
            ACCESS_KEY: "test_access_key"
            REFRESH_KEY: "test_refresh_key"
            ENVIRONMENT: "DEV"
        depends_on:
            - redis

    redis:
        image: redis:latest
        container_name: cashcalc-redis