version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  heroku: circleci/heroku@0.0.10

workflows:
  build:
    jobs:
      - build:
          context: SonarCloud
  deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          context: Heroku
          requires:
            - build
          filters:
            branches:
              only: master
  

jobs:
  build:
    docker:
      - image: cimg/go:1.14
    working_directory: ~/go/src/github.com/IstvanN/cashcalc-backend
    environment:
      PROPERTIES_FILE: /home/circleci/go/src/github.com/IstvanN/cashcalc-backend/app.properties
    steps:
      - checkout
      - run: 
          name: Download dependencies
          command: go get -v -t -d ./...
      - run:
          name: check if app prop is there
          command: ls -l /home/circleci/go/src/github.com/IstvanN/cashcalc-backend/app.properties
      - run: 
          name: Run unit tests and create report
          # command: go test -json ./... > test-report.json
          command: go test -v ./...
      - run:
          name: Create test coverage report
          command: go test -coverprofile=coverage-report.out ./...
      - run:
          name: Run go vet
          command: go vet -json ./... > govet-report.json
      - run:
          name: Build binary
          command: go build -x
      - sonarcloud/scan

